insert into clientes (nombre, apellido, email, create_at) values ('Don', 'Chi', 'no@gmail.com', '2026-09-16');
insert into clientes (nombre, apellido, email, create_at) values ('Don', 'Pe', 'dro@gmail.com', '2026-09-16');
insert into clientes (nombre, apellido, email, create_at) values ('Don', 'Pe', 'pe@gmail.com', '2026-09-16');

insert into productos (nombre, descripcion, precio, stock, create_at) values ('Papa', 'bultoepapa', '5000','150', '2026-09-16');
insert into productos (nombre, descripcion, precio, stock, create_at) values ('Arroz', 'bultoearroz', '1000','200', '2026-09-16');
insert into productos (nombre, descripcion, precio, stock, create_at) values ('Frijol', 'bultoefrijol', '850','100', '2026-09-16');