insert into clientes (nombre, apellido, email, create_at) values ('Don', 'Chim', 'bo@gmail.com', '2026-09-16');
insert into clientes (nombre, apellido, email, create_at) values ('Don', 'Pe', 'dro@gmail.com', '2026-09-16');
insert into clientes (nombre, apellido, email, create_at) values ('Don', 'Pe', 'pe@gmail.com', '2026-09-16');

insert into productos (nombre, descripcion, precio, stock, create_at) values ('Papa', 'bultoepapa', '500','150', '2026-09-16');
insert into productos (nombre, descripcion, precio, stock, create_at) values ('Arroz', 'bultoarroz', '1000','200', '2026-09-16');
insert into productos (nombre, descripcion, precio, stock, create_at) values ('Frijol', 'bultofrijol', '800','100', '2026-09-16');